# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "moymir"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [""]
  s.date = "2012-01-04"
  s.email = ""
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/.gitkeep",
    "moymir.gemspec",
    "init.rb",
    "install",
    "lib/moymir.rb",
    "lib/moymir/config.rb",
    "lib/moymir/engine.rb",
    "lib/moymir/rack/post_canvas_middleware.rb",
    "lib/moymir/rails/controller.rb",
    "lib/moymir/rails/controller/redirects.rb",
    "lib/moymir/rails/controller/url_rewriting.rb",
    "lib/moymir/rails/helpers.rb",
    "lib/moymir/rails/helpers/javascript_helper.rb",
    "lib/moymir/user.rb",
    "lib/moymir/api.rb"
  ]
  s.homepage = ""
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.13"
  s.summary = "Mail.ru integration for Rack & Rails application"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ie_iframe_cookies>, ["~> 0.1.2"])
    else
      s.add_dependency(%q<ie_iframe_cookies>, ["~> 0.1.2"])
    end
  else
    s.add_dependency(%q<ie_iframe_cookies>, ["~> 0.1.2"])
  end
end

